;; (use-package intellij-theme  :ensure t)
;; (use-package leuven-theme :ensure t)
(use-package monokai-theme :ensure t)
(add-to-list 'default-frame-alist '(font . "Hack-12"))
(load-theme 'monokai t)
(provide 'init-theme)
